<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="user-PC" name="Test" tests="5" failures="1" timestamp="10 Nov 2019 20:38:13 GMT" time="0.141" errors="0">
  <testcase name="createcustomertest" time="0.031" classname="com.actitime.genericlib.Testannotationprogram2">
    <failure type="java.lang.ArrayIndexOutOfBoundsException" message="3">
      <![CDATA[java.lang.ArrayIndexOutOfBoundsException: 3
	at com.actitime.genericlib.Testannotationprogram2.createcustomertest(Testannotationprogram2.java:10)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 10 stack frames]]>
    </failure>
  </testcase> <!-- createcustomertest -->
  <testcase name="modifycustomertest" time="0.031" classname="com.actitime.genericlib.Testannotationprogram"/>
  <testcase name="deletecustomertest" time="0.047" classname="com.actitime.genericlib.Testannotationprogram"/>
  <testcase name="createcustomertest" time="0.031" classname="com.actitime.genericlib.Testannotationprogram"/>
  <testcase name="modifycustomertest" time="0.0" classname="com.actitime.genericlib.Testannotationprogram2">
    <skipped/>
  </testcase> <!-- modifycustomertest -->
</testsuite> <!-- Test -->
